name: project
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  sqflite_common_ffi: ^2.0.0+3
  sqflite: ^2.0.0+3
  path_provider: ^2.0.11
  cupertino_icons: ^1.0.8
  hive: ^2.2.3
  hive_flutter: ^1.1.0  # Add this line  path_provider: ^2.0.11
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.0    # Add this line
  hive_generator: ^1.0.0  # Add this line

flutter:

  uses-material-design: true
